# 项目相关配置
dragon:
  # 名称
  name: graduate
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2020
  # 文件路径
  profile: D:/Temp/profile/
  #D:/Temp/profile/
  # 获取ip地址开关
  addressEnabled: true
spring:
  mvc:
    view:
      prifix: /templates/
      suffix: .html
    static-path-pattern: /**
  resources:
      static-locations: classpath:/static/
  # 模板引擎
  thymeleaf:
    prefix: classpath:/templates/
    encoding: utf-8
    # 禁用缓存
    cache: false
    suffix: .html  #mybatis数据源
  datasource:
    url: jdbc:mysql://localhost:3306/graduate?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: a
    driver-class-name: com.mysql.cj.jdbc.Driver
  #邮件发送
  mail:
    #邮箱服务器地址
    host: smtp.qq.com
    username: 869872053@qq.com
    password: sjopyrfmhrhbbcih
    default-ending: UTF-8
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 47.114.163.135
    # Redis端口号
    port: 6379
    # Redis连接密码（一般默认为空）
    password: redis
# web服务器配置
server:
  # 服务器的HTTP端口，默认为80
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
    #配置post提交的参数信息大小设置，不限制
    max-http-form-post-size: -1
#自定义属性，谁发送邮件
mail:
  fromMail:
    addr: 869872053@qq.com
