package com.hhe.graduate.bean;

import lombok.ToString;

@ToString
public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Mon Jan 13 10:49:42 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_name
     *
     * @mbg.generated Mon Jan 13 10:49:42 CST 2020
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_loginName
     *
     * @mbg.generated Mon Jan 13 10:49:42 CST 2020
     */
    private String userLoginname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_pass
     *
     * @mbg.generated Mon Jan 13 10:49:42 CST 2020
     */
    private String userPass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_sex
     *
     * @mbg.generated Mon Jan 13 10:49:42 CST 2020
     */
    private String userSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_head
     *
     * @mbg.generated Mon Jan 13 10:49:42 CST 2020
     */
    private String userHead;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_integrals
     *
     * @mbg.generated Mon Jan 13 10:49:42 CST 2020
     */
    private Integer userIntegrals;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_type
     *
     * @mbg.generated Mon Jan 13 10:49:42 CST 2020
     */
    private String userType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_email
     *
     * @mbg.generated Mon Jan 13 10:49:42 CST 2020
     */
    private String userEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_remark
     *
     * @mbg.generated Mon Jan 13 10:49:42 CST 2020
     */
    private String userRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated Mon Jan 13 10:49:42 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated Mon Jan 13 10:49:42 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_name
     *
     * @return the value of user.user_name
     *
     * @mbg.generated Mon Jan 13 10:49:42 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_name
     *
     * @param userName the value for user.user_name
     *
     * @mbg.generated Mon Jan 13 10:49:42 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_loginName
     *
     * @return the value of user.user_loginName
     *
     * @mbg.generated Mon Jan 13 10:49:42 CST 2020
     */
    public String getUserLoginname() {
        return userLoginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_loginName
     *
     * @param userLoginname the value for user.user_loginName
     *
     * @mbg.generated Mon Jan 13 10:49:42 CST 2020
     */
    public void setUserLoginname(String userLoginname) {
        this.userLoginname = userLoginname == null ? null : userLoginname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_pass
     *
     * @return the value of user.user_pass
     *
     * @mbg.generated Mon Jan 13 10:49:42 CST 2020
     */
    public String getUserPass() {
        return userPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_pass
     *
     * @param userPass the value for user.user_pass
     *
     * @mbg.generated Mon Jan 13 10:49:42 CST 2020
     */
    public void setUserPass(String userPass) {
        this.userPass = userPass == null ? null : userPass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_sex
     *
     * @return the value of user.user_sex
     *
     * @mbg.generated Mon Jan 13 10:49:42 CST 2020
     */
    public String getUserSex() {
        return userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_sex
     *
     * @param userSex the value for user.user_sex
     *
     * @mbg.generated Mon Jan 13 10:49:42 CST 2020
     */
    public void setUserSex(String userSex) {
        this.userSex = userSex == null ? null : userSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_head
     *
     * @return the value of user.user_head
     *
     * @mbg.generated Mon Jan 13 10:49:42 CST 2020
     */
    public String getUserHead() {
        return userHead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_head
     *
     * @param userHead the value for user.user_head
     *
     * @mbg.generated Mon Jan 13 10:49:42 CST 2020
     */
    public void setUserHead(String userHead) {
        this.userHead = userHead == null ? null : userHead.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_integrals
     *
     * @return the value of user.user_integrals
     *
     * @mbg.generated Mon Jan 13 10:49:42 CST 2020
     */
    public Integer getUserIntegrals() {
        return userIntegrals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_integrals
     *
     * @param userIntegrals the value for user.user_integrals
     *
     * @mbg.generated Mon Jan 13 10:49:42 CST 2020
     */
    public void setUserIntegrals(Integer userIntegrals) {
        this.userIntegrals = userIntegrals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_type
     *
     * @return the value of user.user_type
     *
     * @mbg.generated Mon Jan 13 10:49:42 CST 2020
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_type
     *
     * @param userType the value for user.user_type
     *
     * @mbg.generated Mon Jan 13 10:49:42 CST 2020
     */
    public void setUserType(String userType) {
        this.userType = userType == null ? null : userType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_email
     *
     * @return the value of user.user_email
     *
     * @mbg.generated Mon Jan 13 10:49:42 CST 2020
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_email
     *
     * @param userEmail the value for user.user_email
     *
     * @mbg.generated Mon Jan 13 10:49:42 CST 2020
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_remark
     *
     * @return the value of user.user_remark
     *
     * @mbg.generated Mon Jan 13 10:49:42 CST 2020
     */
    public String getUserRemark() {
        return userRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_remark
     *
     * @param userRemark the value for user.user_remark
     *
     * @mbg.generated Mon Jan 13 10:49:42 CST 2020
     */
    public void setUserRemark(String userRemark) {
        this.userRemark = userRemark == null ? null : userRemark.trim();
    }
}